(function(){
  const nav=document.querySelector('.nav');
  if(!nav||document.querySelector('[data-page="teachers"]'))return;
  const roles=['모든','담임','학년부장','상담교사','학생부장','없음'];
  const button=document.createElement('button');
  button.dataset.page='teachers';button.textContent='4. 교사설정';button.onclick=()=>{page='teachers';render()};nav.appendChild(button);
  const oldRender=window.render;
  window.render=function(){
    if(page!=='teachers'){oldRender();return}
    document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===page));
    document.getElementById('page').innerHTML=`<div class="top"><div><h1>4. 교사설정</h1><span class="muted">교사 정보와 권한을 관리합니다. 단축키: 4</span></div></div>
      <div class="card"><div class="field"><label>이름</label><input id="teacherName" placeholder="교사 이름"></div>
      <div class="field"><label>이메일</label><input id="teacherEmail" type="email" placeholder="teacher@example.com"><small id="emailStatus" class="muted"></small></div>
      <div class="field"><label>전화번호 (선택)</label><input id="teacherPhone" type="tel" placeholder="010-0000-0000"><small id="phoneStatus" class="muted"></small></div>
      <div class="field"><label>권한</label><select id="teacherRole">${roles.map(r=>`<option>${r}</option>`).join('')}</select></div>
      <button class="primary" id="saveTeacher">교사 정보 저장</button></div>
      <div class="card"><h2>교사 CSV 일괄 등록</h2><p class="muted">CSV 열 순서: 이름, 이메일, 전화번호 (권한 열 없음)</p><button class="ghost" id="downloadTeacherCsv">CSV 양식 다운로드</button> <label class="primary" for="teacherCsv">CSV 업로드</label><input id="teacherCsv" type="file" accept=".csv,text/csv" style="display:none"><div id="csvStatus" class="muted" style="margin-top:12px;white-space:pre-line"></div></div>
      <div class="card"><h2>등록된 교사</h2><div id="teacherList" class="muted">목록을 불러오는 중입니다.</div></div>`;
    const email=document.getElementById('teacherEmail'),phone=document.getElementById('teacherPhone');
    email.addEventListener('blur',()=>validateEmail(email));phone.addEventListener('blur',()=>validatePhone(phone));
    document.getElementById('saveTeacher').onclick=saveOne;
    document.getElementById('downloadTeacherCsv').onclick=downloadCsv;
    document.getElementById('teacherCsv').onchange=e=>handleCsv(e.target.files[0]);
    loadTeachers();
  };
  function setStatus(id,msg,ok){const e=document.getElementById(id);if(e){e.textContent=msg;e.style.color=ok?'#159875':'#d13b4f'}}
  function validateEmail(el){const ok=/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(el.value.trim());setStatus('emailStatus',el.value?(ok?'사용 가능한 이메일입니다.':'이메일 형식이 올바르지 않습니다.'):'',ok);return ok}
  function validatePhone(el){if(!el.value.trim()){setStatus('phoneStatus','전화번호는 선택 입력입니다.',true);return true}const ok=/^(01[016789])[- .]?\d{3,4}[- .]?\d{4}$/.test(el.value.trim());setStatus('phoneStatus',ok?'사용 가능한 전화번호입니다.':'전화번호 형식이 올바르지 않습니다.',ok);return ok}
  function csvEscape(v){return '"'+String(v??'').replaceAll('"','""')+'"'}
  function downloadCsv(){const csv='이름,이메일,전화번호\r\n홍길동,teacher@example.com,010-0000-0000\r\n';const blob=new Blob([new Uint8Array([0xEF,0xBB,0xBF]),csv],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='teachers-template-utf8.csv';document.body.appendChild(a);a.click();a.remove()}
  function parseCsv(text){return text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(x=>x.trim()).map(line=>{const out=[];let cur='',quote=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'&&line[i+1]==='"'){cur+='"';i++}else if(c==='"')quote=!quote;else if(c===','&&!quote){out.push(cur.trim());cur=''}else cur+=c}out.push(cur.trim());return out})}
  async function saveRows(rows){const clean=rows.map(x=>({...x,role:x.role||'없음'}));if(window.supabase&&window.GLOBALHUB_SUPABASE?.anonKey){const c=supabase.createClient(GLOBALHUB_SUPABASE.url,GLOBALHUB_SUPABASE.anonKey);const r=await c.from('teachers').upsert(clean,{onConflict:'email'});if(r.error)throw r.error}localStorage.setItem('globalhub.teachers',JSON.stringify(clean));}
  async function saveOne(){const n=document.getElementById('teacherName'),e=document.getElementById('teacherEmail'),p=document.getElementById('teacherPhone'),r=document.getElementById('teacherRole');if(!n.value.trim()||!validateEmail(e)||!validatePhone(p)){alert('이름과 이메일을 확인해 주세요.');return}try{await saveRows([{name:n.value.trim(),email:e.value.trim(),phone:p.value.trim()||null,role:r.value,missingRole:false}]);alert('교사 정보가 저장되었습니다.');loadTeachers()}catch(err){alert('저장에 실패했습니다. RLS 정책을 확인해 주세요.')}}
  async function handleCsv(file){if(!file)return;const status=document.getElementById('csvStatus');const set=m=>status.textContent=m;set('1/4 파일을 읽는 중입니다...');await new Promise(r=>setTimeout(r,150));const rows=parseCsv(await file.text());set('2/4 이메일과 전화번호를 검증하는 중입니다...');const errors=[],valid=[];rows.slice(1).forEach((x,i)=>{const line=i+2,name=x[0],email=x[1],phone=x[2]||'';if(!name||!email){errors.push(`${line}행: 이름과 이메일은 필수입니다.`);return}if(!/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(email)){errors.push(`${line}행 (${name}): 이메일 형식 오류`);return}if(phone&&!/^(01[016789])[- .]?\d{3,4}[- .]?\d{4}$/.test(phone)){errors.push(`${line}행 (${name}): 전화번호 형식 오류`);return}valid.push({name,email,phone:phone||null,role:'없음',missingRole:true})});set('3/4 검증 완료\n정상 '+valid.length+'명 / 오류 '+errors.length+'명');if(errors.length)set('3/4 검증 완료\n'+errors.join('\n')+'\n\n정상 '+valid.length+'명 / 오류 '+errors.length+'명');if(valid.length){try{await saveRows(valid);set('4/4 업로드 완료\n'+valid.length+'명 등록되었습니다.\n권한을 각각 설정해 주세요.');loadTeachers()}catch(err){set('저장 오류: RLS 정책을 확인해 주세요.')}}else set('업로드할 정상 행이 없습니다.');}
  async function loadTeachers(){const el=document.getElementById('teacherList');if(!el)return;let rows=[];try{if(window.supabase&&window.GLOBALHUB_SUPABASE?.anonKey){const c=supabase.createClient(window.GLOBALHUB_SUPABASE.url,window.GLOBALHUB_SUPABASE.anonKey);const r=await c.from('teachers').select('name,email,phone,role').order('name');if(!r.error)rows=r.data||[]}}catch(e){}if(!rows.length)rows=JSON.parse(localStorage.getItem('globalhub.teachers')||'[]');if(window.GLOBALHUB_TEST_DATA?.visible)rows=rows.concat(window.GLOBALHUB_TEST_DATA.teachers.map(x=>({name:x[0],email:x[1],phone:x[2],role:x[3],isTest:true})));el.innerHTML=rows.length?'<table class="table"><tr><th>이름</th><th>이메일</th><th>전화번호</th><th>권한</th></tr>'+rows.map((x,i)=>`<tr${x.isTest?' style="background:#fffbea"':''}><td>${x.name}${x.isTest?' <span class="tag">테스트</span>':''}</td><td>${x.email}</td><td>${x.phone||'미등록'}</td><td><select data-teacher-index="${i}" style="${x.missingRole?'border:2px solid #d13b4f;color:#d13b4f':''}"><option value="">권한 선택</option>${roles.map(r=>`<option ${x.role===r&&!x.missingRole?'selected':''}>${r}</option>`).join('')}</select>${x.missingRole?' <small style="color:#d13b4f;font-weight:bold">권한을 설정해 주세요</small>':''}</td></tr>`).join('')+'</table>':'등록된 교사가 없습니다.';el.querySelectorAll('[data-teacher-index]').forEach(s=>s.onchange=async()=>{if(!s.value)return;const x=rows[s.dataset.teacherIndex];x.role=s.value;x.missingRole=false;try{if(x.isTest&&window.GLOBALHUB_TEST_DATA){const t=window.GLOBALHUB_TEST_DATA.teachers.find(v=>v[1]===x.email);if(t)t[3]=s.value;loadTeachers()}else{await saveRows([x]);loadTeachers()}}catch(e){alert('권한 저장에 실패했습니다.')}})}
  document.addEventListener('keydown',e=>{if(!e.ctrlKey&&!e.altKey&&!e.metaKey&&!e.shiftKey&&e.key==='4'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)){e.preventDefault();page='teachers';render()}});
})();
