(function(){
  const style=document.createElement('style');style.textContent='.class-grid,.student-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.class-card,.student-card{background:#fff;border:1px solid #dfe4ec;border-radius:12px;padding:28px;cursor:pointer;text-align:center}.class-card strong{display:block;font-size:28px}.class-card span,.student-card small{display:block;color:#718096;margin-top:8px}.student-photo{display:flex;width:110px;height:110px;margin:auto auto 12px;border-radius:12px;background:#dfe7ff;color:#365cf5;align-items:center;justify-content:center;font-size:38px;font-weight:bold}.student-card b{display:block}@media(max-width:800px){.class-grid,.student-grid{grid-template-columns:repeat(2,1fr)}}';document.head.appendChild(style);
  const teachers=[['김민준','minjun@demo.school','010-1000-0001','담임'],['이서연','seoyeon@demo.school','010-1000-0002','학년부장'],['박지훈','jihoon@demo.school','010-1000-0003','상담교사'],['최유진','yujin@demo.school','010-1000-0004','학생부장'],['Nguyen Lan','lan@demo.school','010-1000-0005','없음'],['Aziz Karimov','aziz@demo.school','010-1000-0006','모든']];
  const students=Array.from({length:12},(_,i)=>({name:['김하늘','이도윤','박서준','최지우','Nguyen Minh Anh','Tran Hoang Nam','Azizbek Karimov','Dilnoza Saidova','정유나','한지민','오세훈','윤서아'][i],klass:i<6?'A반':'B반',country:i%2?'베트남':'우즈베키스탄',initial:['김','이','박','최','N','T','A','D','정','한','오','윤'][i]}));
  window.GLOBALHUB_TEST_DATA={teachers,students,visible:false};
  const nav=document.querySelector('.nav');if(nav&&!document.getElementById('testToggle')){const b=document.createElement('button');b.id='testToggle';b.className='ghost';b.textContent='테스트 데이터 보기';b.onclick=()=>{GLOBALHUB_TEST_DATA.visible=!GLOBALHUB_TEST_DATA.visible;b.textContent=GLOBALHUB_TEST_DATA.visible?'테스트 데이터 숨기기':'테스트 데이터 보기';render()};nav.parentElement.appendChild(b)}
  const prior=window.render;window.render=function(){if(page==='classes'||page==='classStudents'||page==='survey'){document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.page==='students'));document.getElementById('page').innerHTML=page==='classes'?classPage():page==='classStudents'?classStudentsPage():surveyPage();return}prior();if(page==='students'&&GLOBALHUB_TEST_DATA.visible)document.getElementById('page').innerHTML=testStudentsPage()};
  function testStudentsPage(){return '<div class="top"><div><h1>2. 학생관리</h1><span class="muted">테스트 학생 12명 · 반을 선택해 조회하세요.</span></div></div><div class="card"><h2>테스트 교사 6명</h2><p class="muted">'+teachers.map(x=>x[0]+' · '+x[1]+' · '+x[3]).join('<br>')+'</p></div>'+classPage()}
  function classPage(){return '<div class="top"><div><h1>반 선택</h1><span class="muted">조회할 반을 선택하세요.</span></div><button class="ghost" onclick="page=\'survey\';render()">학생 설문 테스트</button></div><div class="class-grid">'+['A반','B반'].map(k=>'<button class="class-card" onclick="selectedClass=\''+k+'\';page=\'classStudents\';render()"><strong>'+k+'</strong><span>'+students.filter(s=>s.klass===k).length+'명</span></button>').join('')+'</div>'}
  function classStudentsPage(){let list=students.filter(s=>s.klass===selectedClass);return '<div class="top"><div><h1>'+selectedClass+' 학생</h1><span class="muted">학생을 선택하면 상세 화면으로 이동합니다.</span></div><button class="ghost" onclick="page=\'classes\';render()">← 반 목록</button></div><div class="student-grid">'+list.map(s=>'<button class="student-card"><span class="student-photo">'+s.initial+'</span><b>'+s.name+'</b><small>'+s.country+'</small></button>').join('')+'</div>'}
  function surveyPage(){return '<div class="survey"><div class="top"><div><h1>학생 기초조사</h1><span class="muted">테스트 설문 작성 화면</span></div><button class="ghost" onclick="page=\'classes\';render()">닫기</button></div><div class="card"><div class="field"><label>언어 선택</label><select><option>한국어</option><option>Tiếng Việt</option><option>Oʻzbekcha</option></select></div><div class="field"><label>프로필 사진</label><input type="file" accept="image/*" capture="user"><small class="muted">휴대폰 카메라 촬영 또는 갤러리 선택</small></div>'+questions.filter(q=>q[2]!==false).slice(0,8).map((q,i)=>'<div class="field"><label>'+(i+1)+'. '+q[0]+'</label><input placeholder="답변을 입력해 주세요"></div>').join('')+'<button class="primary" onclick="alert(\'테스트 설문이 저장되었습니다.\')">제출 테스트</button></div></div>'}
  window.selectedClass='A반';
})();
